<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DEV_ProductTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $productData = [
            // Action Figures
            [
                'code' => 'AF001',
                'quantity' => 10,
                'label_ita' => 'Superman',
                'label_eng' => 'Superman',
                'year' => 2000,
                'description_ita' => 'Superman action figure con dettagli realistici. in italiano.',
                'description_eng' => 'Superman action figure with realistic details.',
                'price' => 99,
                'in_evidence' => true,
                'condition_id' => 1,
                'draft' => true,
                'deleting' => false,
                'creator' => 'DC Comics',
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                'code' => 'AF002',
                'quantity' => 15,
                'label_ita' => 'Batman',
                'label_eng' => 'Batman',
                'year' => 2005,
                'description_ita' => 'Batman action figure con bat-segnale. in italiano.',
                'description_eng' => 'Batman action figure with bat-signal.',
                'price' => 120,
                'in_evidence' => true,
                'condition_id' => 1,
                'draft' => false,
                'deleting' => false,
                'creator' => 'DC Comics',
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                'code' => 'AF003',
                'quantity' => 8,
                'label_ita' => 'Captain America',
                'label_eng' => 'Captain America',
                'year' => 2010,
                'description_ita' => 'Captain America con scudo. in italiano.',
                'description_eng' => 'Captain America with shield.',
                'price' => 110,
                'in_evidence' => true,
                'condition_id' => 1,
                'draft' => true,
                'deleting' => false,
                'creator' => 'Marvel',
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                'code' => 'AF004',
                'quantity' => 12,
                'label_ita' => 'Hulk',
                'label_eng' => 'Hulk',
                'year' => 2011,
                'description_ita' => 'Hulk in posa da combattimento. in italiano.',
                'description_eng' => 'Hulk in combat pose.',
                'price' => 130,
                'in_evidence' => true,
                'condition_id' => 1,
                'draft' => false,
                'deleting' => false,
                'creator' => 'Marvel',
                "created_at" => now(),
                "updated_at" => now()
            ],
            // Giochi in scatola
            [
                'code' => 'BG001',
                'quantity' => 20,
                'label_ita' => 'Monopoly Italia',
                'label_eng' => 'Monopoly Italy',
                'year' => 2010,
                'description_ita' => 'Versione italiana del classico gioco da tavolo. in italiano.',
                'description_eng' => 'Italian version of the classic board game.',
                'price' => 35,
                'in_evidence' => false,
                'condition_id' => 1,
                'draft' => false,
                'deleting' => false,
                'creator' => 'Hasbro',
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                'code' => 'BG002',
                'quantity' => 30,
                'label_ita' => 'Risiko!',
                'label_eng' => 'Risiko!',
                'year' => 2012,
                'description_ita' => 'Gioco di strategia per conquistare il mondo. in italiano.',
                'description_eng' => 'Strategy game to conquer the world.',
                'price' => 45,
                'in_evidence' => true,
                'condition_id' => 1,
                'draft' => false,
                'deleting' => false,
                'creator' => 'Editrice Giochi',
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                'code' => 'BG003',
                'quantity' => 15,
                'label_ita' => 'Cluedo',
                'label_eng' => 'Cluedo',
                'year' => 2014,
                'description_ita' => 'Gioco di mistero e investigazione. in italiano.',
                'description_eng' => 'Mystery and investigation game.',
                'price' => 40,
                'in_evidence' => true,
                'condition_id' => 1,
                'draft' => false,
                'deleting' => true,
                'creator' => 'Hasbro',
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                'code' => 'BG004',
                'quantity' => 25,
                'label_ita' => 'Trivial Pursuit',
                'label_eng' => 'Trivial Pursuit',
                'year' => 2011,
                'description_ita' => 'Gioco di domande e risposte. in italiano.',
                'description_eng' => 'Question and answer game.',
                'price' => 50,
                'in_evidence' => true,
                'condition_id' => 1,
                'draft' => false,
                'deleting' => false,
                'creator' => 'Hasbro',
                "created_at" => now(),
                "updated_at" => now()
            ],
            // Bambole
            [
                'code' => 'DL001',
                'quantity' => 50,
                'label_ita' => 'Bambola Barbie Fashionista',
                'label_eng' => 'Barbie Fashionista Doll',
                'year' => 2015,
                'description_ita' => 'Barbie con outfit alla moda. in italiano.',
                'description_eng' => 'Barbie with fashionable outfit.',
                'price' => 25,
                'in_evidence' => false,
                'condition_id' => 1,
                'draft' => false,
                'deleting' => false,
                'creator' => 'Mattel',
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                'code' => 'DL002',
                'quantity' => 40,
                'label_ita' => 'Bambola Bratz Yasmin',
                'label_eng' => 'Bratz Doll Yasmin',
                'year' => 2013,
                'description_ita' => 'Yasmin della serie Bratz con accessori. in italiano.',
                'description_eng' => 'Yasmin from Bratz series with accessories.',
                'price' => 30,
                'in_evidence' => true,
                'condition_id' => 1,
                'draft' => false,
                'deleting' => false,
                'creator' => 'MGA Entertainment',
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                'code' => 'DL0033', 
                'quantity' => 35,
                'label_ita' => 'Bambola My Little Pony',
                'label_eng' => 'My Little Pony Doll',
                'year' => 2018,
                'description_ita' => 'Bambola ispirata alla serie My Little Pony. in italiano.',
                'description_eng' => 'Doll inspired by My Little Pony series.',
                'price' => 28,
                'in_evidence' => true,
                'condition_id' => 1,
                'draft' => false,
                'deleting' => true,
                'creator' => 'Hasbro',
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                'code' => 'DL004',
                'quantity' => 30,
                'label_ita' => 'Frozen Elsa',
                'label_eng' => 'Frozen Elsa',
                'year' => 2017,
                'description_ita' => 'Elsa del film Frozen con abito scintillante. in italiano.',
                'description_eng' => 'Elsa from Frozen movie with sparkling dress.',
                'price' => 32,
                'in_evidence' => true,
                'condition_id' => 1,
                'draft' => false,
                'deleting' => false,
                'creator' => 'Disney',
                "created_at" => now(),
                "updated_at" => now()
            ],
            // Robot
            [
                'code' => 'RB001',
                'quantity' => 10,
                'label_ita' => 'Robot Trasformabile',
                'label_eng' => 'Transformable Robot',
                'year' => 2020,
                'description_ita' => 'Robot che si trasforma in vari veicoli. in italiano.',
                'description_eng' => 'Robot that transforms into various vehicles.',
                'price' => 75,
                'in_evidence' => false,
                'condition_id' => 1,
                'draft' => true,
                'deleting' => false,
                'creator' => 'Takara Tomy',
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                'code' => 'RB002',
                'quantity' => 8,
                'label_ita' => 'Robot Asimo',
                'label_eng' => 'Asimo Robot',
                'year' => 2018,
                'description_ita' => 'Replica del famoso robot Asimo. in italiano.',
                'description_eng' => 'Replica of the famous Asimo robot.',
                'price' => 150,
                'in_evidence' => true,
                'condition_id' => 1,
                'draft' => true,
                'deleting' => false,
                'creator' => 'Honda',
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                'code' => 'RB003',
                'quantity' => 5,
                'label_ita' => 'Robot Wall-E',
                'label_eng' => 'Wall-E Robot',
                'year' => 2015,
                'description_ita' => 'Replica del robot Wall-E del film Disney. in italiano.',
                'description_eng' => 'Replica of Wall-E robot from Disney movie.',
                'price' => 140,
                'in_evidence' => true,
                'condition_id' => 1,
                'draft' => false,
                'deleting' => false,
                'creator' => 'Disney',
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                'code' => 'RB004',
                'quantity' => 7,
                'label_ita' => 'Robot BB-8',
                'label_eng' => 'BB-8 Robot',
                'year' => 2019,
                'description_ita' => 'Replica del robot BB-8 di Star Wars. in italiano.',
                'description_eng' => 'Replica of BB-8 robot from Star Wars.',
                'price' => 135,
                'in_evidence' => true,
                'condition_id' => 1,
                'draft' => true,
                'deleting' => false,
                'creator' => 'Star Wars',
                "created_at" => now(),
                "updated_at" => now()
            ],
            // Marvel (sotto categoria di "Action Figures" e "Comics")
            [
                'code' => 'MRV001',
                'quantity' => 12,
                'label_ita' => 'Action Figure Iron Man',
                'label_eng' => 'Iron Man Action Figure',
                'year' => 2015,
                'description_ita' => 'Iron Man con armatura dettagliata. in italiano.',
                'description_eng' => 'Iron Man with detailed armor.',
                'price' => 99,
                'in_evidence' => true,
                'condition_id' => 1,
                'draft' => false,
                'deleting' => false,
                'creator' => 'Marvel',
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                'code' => 'MRV002',
                'quantity' => 20,
                'label_ita' => 'Action Figure Spider-Man',
                'label_eng' => 'Spider-Man Action Figure',
                'year' => 2016,
                'description_ita' => 'Spider-Man con dettagli della tuta. in italiano.',
                'description_eng' => 'Spider-Man with suit details.',
                'price' => 85,
                'in_evidence' => true,
                'condition_id' => 1,
                'draft' => false,
                'deleting' => false,
                'creator' => 'Marvel',
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                'code' => 'MRV003',
                'quantity' => 18,
                'label_ita' => 'Action Figure Thor',
                'label_eng' => 'Thor Action Figure',
                'year' => 2017,
                'description_ita' => 'Thor con martello Mjolnir. in italiano.',
                'description_eng' => 'Thor with Mjolnir hammer.',
                'price' => 95,
                'in_evidence' => true,
                'condition_id' => 1,
                'draft' => false,
                'deleting' => false,
                'creator' => 'Marvel',
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                'code' => 'MRV004',
                'quantity' => 22,
                'label_ita' => 'Action Figure Black Panther',
                'label_eng' => 'Black Panther Action Figure',
                'year' => 2018,
                'description_ita' => 'Black Panther con costume vibranio. in italiano.',
                'description_eng' => 'Black Panther with vibranium suit.',
                'price' => 105,
                'in_evidence' => true,
                'condition_id' => 1,
                'draft' => true,
                'deleting' => false,
                'creator' => 'Marvel',
                "created_at" => now(),
                "updated_at" => now()
            ],
            // DC (sotto categoria di "Action Figures" e "Comics")
            [
                'code' => 'DC001',
                'quantity' => 15,
                'label_ita' => 'Action Figure Wonder Woman',
                'label_eng' => 'Wonder Woman Action Figure',
                'year' => 2017,
                'description_ita' => 'Wonder Woman con lasso e scudo. in italiano.',
                'description_eng' => 'Wonder Woman with lasso and shield.',
                'price' => 95,
                'in_evidence' => true,
                'condition_id' => 1,
                'draft' => false,
                'deleting' => false,
                'creator' => 'DC Comics',
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                'code' => 'DC002',
                'quantity' => 25,
                'label_ita' => 'Action Figure Flash',
                'label_eng' => 'Flash Action Figure',
                'year' => 2018,
                'description_ita' => 'Flash con dettagli della tuta. in italiano.',
                'description_eng' => 'Flash with suit details.',
                'price' => 89,
                'in_evidence' => true,
                'condition_id' => 1,
                'draft' => false,
                'deleting' => false,
                'creator' => 'DC Comics',
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                'code' => 'DC003',
                'quantity' => 10,
                'label_ita' => 'Action Figure Aquaman',
                'label_eng' => 'Aquaman Action Figure',
                'year' => 2019,
                'description_ita' => 'Aquaman con tridente. in italiano.',
                'description_eng' => 'Aquaman with trident.',
                'price' => 90,
                'in_evidence' => true,
                'condition_id' => 1,
                'draft' => false,
                'deleting' => false,
                'creator' => 'DC Comics',
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                'code' => 'DC004',
                'quantity' => 14,
                'label_ita' => 'Action Figure Green Lantern',
                'label_eng' => 'Green Lantern Action Figure',
                'year' => 2020,
                'description_ita' => 'Green Lantern con anello del potere. in italiano.',
                'description_eng' => 'Green Lantern with power ring.',
                'price' => 85,
                'in_evidence' => true,
                'condition_id' => 1,
                'draft' => false,
                'deleting' => false,
                'creator' => 'DC Comics',
                "created_at" => now(),
                "updated_at" => now()
            ],
            // Comics (Categoria principale)
            [
                'code' => 'CM001',
                'quantity' => 50,
                'label_ita' => 'Fumetto Iron Man #1',
                'label_eng' => 'Iron Man Comic #1',
                'year' => 1968,
                'description_ita' => 'Il primo fumetto di Iron Man. in italiano.',
                'description_eng' => 'The first Iron Man comic.',
                'price' => 150,
                'in_evidence' => true,
                'condition_id' => 1,
                'draft' => false,
                'deleting' => false,
                'creator' => 'Stan Lee',
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                'code' => 'CM002',
                'quantity' => 40,
                'label_ita' => 'Fumetto Batman: Year One',
                'label_eng' => 'Batman: Year One Comic',
                'year' => 1987,
                'description_ita' => 'Storia delle origini di Batman. in italiano.',
                'description_eng' => 'Batman origin story.',
                'price' => 95,
                'in_evidence' => true,
                'condition_id' => 1,
                'draft' => false,
                'deleting' => false,
                'creator' => 'Frank Miller',
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                'code' => 'CM003',
                'quantity' => 45,
                'label_ita' => 'Fumetto Spider-Man: The Night Gwen Stacy Died',
                'label_eng' => 'Spider-Man: The Night Gwen Stacy Died Comic',
                'year' => 1973,
                'description_ita' => 'Spider-Man con storia epica. in italiano.',
                'description_eng' => 'Spider-Man with epic story.',
                'price' => 120,
                'in_evidence' => true,
                'condition_id' => 1,
                'draft' => true,
                'deleting' => false,
                'creator' => 'Marvel',
                "created_at" => now(),
                "updated_at" => now()
            ],
            [
                'code' => 'CM004',
                'quantity' => 55,
                'label_ita' => 'Superman: Red Son',
                'label_eng' => 'Superman: Red Son',
                'year' => 2003,
                'description_ita' => 'Superman in una realtà alternativa. in italiano.',
                'description_eng' => 'Superman in an alternate reality.',
                'price' => 110,
                'in_evidence' => true,
                'condition_id' => 1,
                'draft' => True,
                'deleting' => false,
                'creator' => 'DC Comics',
                "created_at" => now(),
                "updated_at" => now()
            ],
        ];

        DB::table('products')->insert($productData);
    }
}
